Description of cba_reduce_to_active_subnetwork
Home > metabolic-economics > metabolic-economics-utils > cba_reduce_to_active_subnetwork.m
cba_reduce_to_active_subnetwork
PURPOSE
[v,N_int,Es,network_act,constraints,ind_active,ind_met_active] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,constraints)
SYNOPSIS
function [v,N_int,Es,network_act,constraints,ind_active,ind_met_active] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,constraints)
DESCRIPTION
 [v,N_int,Es,network_act,constraints,ind_active,ind_met_active] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,constraints)
 Reduce cba problem with flux mode v to a cba problem on the active subnetwork
CROSS-REFERENCE INFORMATION
This function calls:
cba_constraints_reduce_to_active CBA_CONSTRAINTS_REDUCE_TO_ACTIVE - Remove inactive reactions in cba_constraints
This function is called by:
cba_adjust_fluxes CBA_ADJUST_FLUXES - Correct a flux mode to make it economical
cba_feasible_cycle CBA_FEASIBLE_CYCLE - Check economical flux distribution (non-beneficial cycle criterion)
cba_feasible_lp CBA_FEASIBLE_LP - Check flux mode for EFA feasibility and choose enzyme costs and thermodynamic forces
cba_reconstruct_model CBA_RECONSTRUCT_MODEL - Build model from economical flux profile
cba_reconstruct_model_OLD CBA_RECONSTRUCT_MODEL - Build model from economical flux profile
SOURCE CODE
function [v,N_int,Es,network_act,constraints,ind_active,ind_met_active] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,constraints)
% [v,N_int,Es,network_act,constraints,ind_active,ind_met_active] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,constraints)
%
% Reduce cba problem with flux mode v to a cba problem on the active subnetwork
eval(default('Es','[]','network','[]'));
epsilon_v_off = 10^-8;
ind_active = find(abs(v)>epsilon_v_off);
v          = v(ind_active);
N_int      = N_int(:,ind_active);
N_int      = N_int(find(sum(N_int~=0,2)),:);
if ~isempty(Es),
  Es = Es(ind_active,:);
end
if ~isempty(network),
%  network = network_choose(network,1:length(network.metabolites),ind_active);
  [network_act,ind_met_active] = network_choose(network,[],ind_active);
end
if exist('constraints','var'),
  constraints = cba_constraints_reduce_to_active(constraints,ind_active,ind_met_active,network,network_act);
else
  constraints = [];
end