Description of cba_update_constraints
Home > metabolic-economics > metabolic-economics-utils > cba_update_constraints.m
cba_update_constraints
PURPOSE
cba_constraints = cba_update_constraints(cba_constraints,Next)
SYNOPSIS
function cba_constraints = cba_update_constraints(cba_constraints,Next,network)
DESCRIPTION
 cba_constraints = cba_update_constraints(cba_constraints,Next)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cba_feasible_cycle CBA_FEASIBLE_CYCLE - Check economical flux distribution (non-beneficial cycle criterion)
cba_feasible_lp CBA_FEASIBLE_LP - Check flux mode for EFA feasibility and choose enzyme costs and thermodynamic forces
cba_homogeneous_cost CBA_HOMOGENEOUS_COST - Determine economic potentials from the principle of even cost
cba_constraints_reduce_to_active CBA_CONSTRAINTS_REDUCE_TO_ACTIVE - Remove inactive reactions in cba_constraints
SOURCE CODE
function cba_constraints = cba_update_constraints(cba_constraints,Next,network)
% cba_constraints = cba_update_constraints(cba_constraints,Next)
cba_constraints.dmu_min(cba_constraints.dmu_sign>0) = 0;
cba_constraints.dmu_max(cba_constraints.dmu_sign<0) = 0;
if length(cba_constraints.z_ext),
  zv = Next' * cba_constraints.z_ext + cba_constraints.z_int;
else,
  cba_constraints.z_ext = zeros(size(Next,1),1);
  zv = cba_constraints.z_int;
end
if isfield(cba_constraints,'zv'),
  if length(cba_constraints.zv),
    if sum(zv ~= cba_constraints.zv)
      warning('Changing existing entry zv');
    end
  end
end
cba_constraints.zv = zv;
cba_constraints = fba_update_constraints(cba_constraints,network);