Description of cba_flux2model_mrl
Home > cba > cba_flux2model_mrl.m
cba_flux2model_mrl
PURPOSE
CBA_FLUX2MODEL_MRL - Construct kinetic model from economical flux mode
SYNOPSIS
function [res, result_act, ind_act, ind_met_act] = cba_flux2model_mrl(network, v, cba_constraints)
DESCRIPTION
 CBA_FLUX2MODEL_MRL - Construct kinetic model from economical flux mode
 [res, result_act, ind_act, ind_met_act] = cba_flux2model_mrl(network, v, cba_constraints)
 cba_constraints.zx_scaled_min minimal scaled enzyme cost (scalar, same minimum for each enzyme)
CROSS-REFERENCE INFORMATION
This function calls:
cba_flux2model_mrl CBA_FLUX2MODEL_MRL - Construct kinetic model from economical flux mode
cba_flux2model_mrl_constraint [g, geq, Ec_un, beta_M, beta_A, beta_I, CJ] = cba_flux2model_mrl_constraint(beta_M_vector,Mplus,Mminus,Wplus,Wminus,E_sc_T,v,c,N,ind_ext,cba_constraints,kinetic_law)
cba_flux2model_mrl_constraint_xi function [g, geq, Ec_un, beta_M, beta_A, beta_I, c, mu, CJ] = cba_flux2model_mrl_constraint_xi(xi,Mplus,Mminus,Wplus,Wminus,v,N,ind_ext,cba_constraints,kinetic_law)
cba_reduce_to_active_subnetwork [v,N_int,Es,network_act,constraints,ind_active,ind_met_active] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,constraints)
This function is called by:
cba_flux2model_mrl CBA_FLUX2MODEL_MRL - Construct kinetic model from economical flux mode
SOURCE CODE
function [res, result_act, ind_act, ind_met_act] = cba_flux2model_mrl(network, v, cba_constraints)
% CBA_FLUX2MODEL_MRL - Construct kinetic model from economical flux mode
%
% [res, result_act, ind_act, ind_met_act] = cba_flux2model_mrl(network, v, cba_constraints)
%
% cba_constraints.zx_scaled_min minimal scaled enzyme cost (scalar, same minimum for each enzyme)
v(find(abs(v)<10^-10)) = 0;
if find(v==0),
  %% reduce to active subnetwork
  %% the following three variables are just dummy inputs
  N_int = network.N(find(network.external==0),:);
  Es = -network.N';
  [v_act,N_int_act,Es_act,network_act,cba_constraints_act,ind_act,ind_met_act] = cba_reduce_to_active_subnetwork(v,N_int,Es,network,cba_constraints);
  figure(1999);
  netgraph_concentrations(network_act,[],v_act,1,struct('actstyle','none'));
  title('Fluxes on active subnetwork');
  [res_act, result_act] = cba_flux2model_mrl(network_act,v_act,cba_constraints_act);
  [nm,nr] = size(network.N);
  res.w       = nan * ones(nm,1);   res.w(ind_met_act)   = res_act.w;
  res.delta_w = nan * ones(nr,1);   res.delta_w(ind_act) = res_act.delta_w;
  res.zx      = nan * ones(nr,1);   res.zx(ind_act)      = res_act.zx;
  res.mu      = nan * ones(nm,1);   res.mu(ind_met_act)  = res_act.mu;
  warning('Data structure "result" describes only the active subnetwork')
  return
end
N        = network.N;
[nm, nr] = size(N);
W        = network.regulation_matrix;
ind_ext  = find(network.external);
ind_int  = find(network.external==0);
stop = 0;
while ~stop,
% -----------------------------------------------------------
% sample energetically feasible stationary state
[es_options,es_constraints] = es_default_options(network);
es_constraints.v_fix         = v;
es_constraints.Keq           = nan * ones(size(network.actions));
es_options.flag_second_order = 0;
es_options.set_alpha_to_half = 0;
[Mplus, Mminus, Wplus, Wminus, nm, nr, N_int] = make_structure_matrices(N, network.regulation_matrix, ind_ext,es_options.h);
M      = Mplus + Mminus;
beta_vector      = 0.5  * ones(sum(M(:)~=0)+sum(W(:)~=0),1);
beta_vector_min  = 0.00001 * ones(size(beta_vector));
beta_vector_max  = 0.99999 * ones(size(beta_vector));
kinetic_law = 'ms';
opt               = optimset('fmincon');
opt.MaxFunEvals   = 1000000;
variant = 'sample c';
switch variant,
  case 'predefine c',
  [c0, c, u, J, Keq, Jred, mu, K, Kma, zeta, A] = es_sample_stationary(N, network.regulation_matrix, ind_ext, es_constraints, es_options);
  E_sc_T = diag(zeta./[zeta-1]) * Mplus - diag(1./[zeta-1]) * Mminus;
  [beta_vector_opt,fval,exitflag] = fmincon(@(E_vector)sum([beta_vector-0.5].^2), beta_vector,[],[],[],[],beta_vector_min,beta_vector_max, @(beta_vector)cba_flux2model_mrl_constraint(beta_vector,Mplus,Mminus,Wplus,Wminus,E_sc_T,v,c,N,ind_ext, cba_constraints,kinetic_law),opt);
  [g, geq, Ec_un, beta_M, beta_A, beta_I, CJ] = cba_flux2model_mrl_constraint(beta_vector_opt,Mplus,Mminus,Wplus,Wminus,E_sc_T,v,c,N,ind_ext,cba_constraints,kinetic_law);
  case 'sample c',
    mu0       =   zeros(nm,1);
    mu0_min   = - 20*ones(nm,1);
    mu0_max   =   20*ones(nm,1);
    dmu_guess = - tanh(v .* rand(size(v)));
    ln_c      =   [pinv(full(N)') * dmu_guess - mu0]/RT; % heuristics for first guess
    ln_c_min  = - 20 * ones(nm,1);
    ln_c_max  =   20 * ones(nm,1);
    xi     = [mu0; ln_c; beta_vector];
    xi_min = [mu0_min; ln_c_min; beta_vector_min];
    xi_max = [mu0_max; ln_c_max; beta_vector_max];
    [xi_opt,fval,exitflag] = fmincon(@(xi)1, xi,[],[],[],[],xi_min,xi_max, @(xi)cba_flux2model_mrl_constraint_xi(xi,Mplus,Mminus,Wplus,Wminus,v,N,ind_ext, cba_constraints,kinetic_law),opt);
    [g, geq, Ec_un, beta_M, beta_A, beta_I, c, mu, CJ] = cba_flux2model_mrl_constraint_xi(xi_opt,Mplus,Mminus,Wplus,Wminus,v,N,ind_ext,cba_constraints,kinetic_law);
end
if exitflag==1,
  stop = 1;
else
  display(sprintf('No solution found\n'));
end
%   g
%     v
     A = -N'*mu;
%     Keq - N'*log(c)
    Cz    = [cba_constraints.zv' * CJ * diag(v)]';
%   Cz    = [CJ(end-1,:) * diag(v)]';
%   Cz    = [CJ(end-2,:) * diag(v)]';
   figure(1000); netgraph_concentrations(network,[],Cz,1,struct('arrowstyle','none')); drawnow
   title('Enzyme control of metabolic benefit (from sampling)')
   figure(1001); netgraph_concentrations(network,[],sign(Cz),1,struct('arrowstyle','none')); drawnow
   title('Enzyme control sign of metabolic benefit (from sampling)')
   figure(1002); netgraph_concentrations(network,[],sign(A.*v),1,struct('arrowstyle','none')); drawnow
   title('Correct flux directions?')
   figure(1003); netgraph_concentrations(network,[],sign(v),1,struct('actstyle','none')); drawnow
   title('Flux directions?')
  figure(1004); im(CJ,[],network.actions);
end
switch variant,
  case 'predefine c',
    [g, geq, Ec_un, beta_M] = cba_flux2model_mrl_constraint(beta_vector_opt,Mplus,Mminus,Wplus,Wminus,E_sc_T,v,c,N,ind_ext,cba_constraints,kinetic_law);
  case 'sample c',
    [g, geq, Ec_un, beta_M, beta_A, beta_I, c, mu] = cba_flux2model_mrl_constraint_xi(xi_opt,Mplus,Mminus,Wplus,Wminus,v,N,ind_ext,cba_constraints,kinetic_law);
end
if find(isnan(g)), error; end
es_constraints.beta_M_fix = beta_M;
es_constraints.log_c_fix  = log(c);
es_constraints.mu_fix     = mu;
es_options.kinetic_law    = kinetic_law;
result_act = sample_model(N,W,ind_ext,es_constraints,es_options);
% check: do all enzymes have a positive control on the benefit?
if sum([[cba_constraints.zv' * result_act.control.CJ]' < cba_constraints.zx_scaled_min * ones(nr,1)]),
  [[cba_constraints.zv' * result_act.control.CJ]', cba_constraints.zx_scaled_min * ones(nr,1)]
  warning('Economically infeasible state encountered!')
end
% -----------------------------------------------------------
N_int = N(ind_int,:);
Ec_un_int = result_act.elasticities.un_E_c(:,ind_int);
w_int   = -[cba_constraints.zv' * Ec_un_int * pinv(N_int * Ec_un_int)]';
delta_w = N_int'*w_int;
zx      = diag(v) * [[delta_w + cba_constraints.zv] ./ cba_constraints.u];
w = nan * ones(nm,1);
w(ind_int) = w_int;
res.w       = w;
res.zx      = zx;
res.delta_w = delta_w;
res.mu      = result_act.mu;