Description of cba_sample_kinetic_model
Home > cba > cba_sample_kinetic_model.m
cba_sample_kinetic_model
PURPOSE
CBA_SAMPLE_KINETIC_MODEL - Sample an enzyme-balanced kinetic model
SYNOPSIS
function [network,result,ind_shut_off,zx,zv,delta_w,w_int,w_ext] = cba_sample_kinetic_model(network,v,cba_constraints,cba_options)
DESCRIPTION
 CBA_SAMPLE_KINETIC_MODEL - Sample an enzyme-balanced kinetic model
 [network,result,ind_shut_off,zx,zv,delta_w,w_int,w_ext] = cba_sample_kinetic_model(network,v,cba_constraints,cba_options)
  uses cba_constraints.zv to define benefit function
  v must be fba/eba/cba-feasible (for check, set cba_options.test_cba = 1)
CROSS-REFERENCE INFORMATION
This function calls:
cba_sample_kinetic_model CBA_SAMPLE_KINETIC_MODEL - Sample an enzyme-balanced kinetic model
cba_update_constraints cba_constraints = cba_update_constraints(cba_constraints,Next)
This function is called by:
cba_sample_kinetic_model CBA_SAMPLE_KINETIC_MODEL - Sample an enzyme-balanced kinetic model
SOURCE CODE
function [network,result,ind_shut_off,zx,zv,delta_w,w_int,w_ext] = cba_sample_kinetic_model(network,v,cba_constraints,cba_options)
% CBA_SAMPLE_KINETIC_MODEL - Sample an enzyme-balanced kinetic model
%
% [network,result,ind_shut_off,zx,zv,delta_w,w_int,w_ext] = cba_sample_kinetic_model(network,v,cba_constraints,cba_options)
%
%  uses cba_constraints.zv to define benefit function
%  v must be fba/eba/cba-feasible (for check, set cba_options.test_cba = 1)
% test: branch point network
if 0,
  cd ~/matlab/projects/cba/cba_models;
  load cba_branch_network;
  v = [2 2 1 1 1 1 1 1]';
  [cba_options,cba_constraints] = cba_default_cba_options(network);
  cba_constraints.z_ext = [1 2 2]';
  cba_constraints.zc = zeros(6,1);
  [network,result,ind_shut_off,zx,zv,delta_w,w_all] = cba_sample_kinetic_model(network,v,cba_constraints,cba_options);
  netgraph_concentrations(network,w_all,delta_w+zv,0,struct('arrowstyle','fluxes','actstyle','none'));
end
epsilon = 10^-8;
cba_constraints = cba_update_constraints(cba_constraints);
% -----------------------------------------------------------
% check necessary condition for cba-feasibility
% initialisation
ind_ext = find(network.external);
ind_int = find(network.external==0);
w_ind   = [];
delta_w = [];
zv      = [];
cba_options.test_eba = 1;
%[cba_feasible,zx_scaled,delta_mu] = cba_feasible_lp(v, network.N, network.external, cba_constraints, cba_options);
% -----------------------------------------------------------
% sample elasticities and create the model
[es_options,es_constraints] = es_default_options(network);
es_constraints.v_fix = v;
es_constraints.Keq   = nan * ones(size(network.actions));
es_options.flag_second_order = 0;
es_options.set_alpha_to_half = 0;
result = sample_model(network.N,network.regulation_matrix,find(network.external),es_constraints,es_options);
network.kinetics = result.kinetics;
% compute enzyme cost: cost must be balanced by marginal benefit
zx = [cba_constraints.zv' * result.control.RJu_un]';
if ~isempty(cba_constraints.zc),
  zx = zx + [cba_constraints.zc' * result.control.RSu_un]';
end
 netgraph_concentrations(network_CoHid,network.external,zx,1,struct('arrowvalues',v,'actstyle','fixed'))
%netgraph_concentrations(network_CoHid,network.external,result.control.RJu_un(end,:)',1,struct('arrowvalues',v,'actstyle','fixed'))
%netgraph_concentrations(network_CoHid,network.external,result.control.RJu_un(end-1,:)',1,struct('arrowvalues',v,'actstyle','fixed'))
ind_shut_off = find((zx<=0) .* (abs(v)> epsilon));
if length(ind_shut_off),
  warning('It appears that some enzymes should be shut off');
end;
% -----------------------------------------------------------
% compute the metabolite values
[K, L, NR, G, pinv_N_R, indep] = network_analyse(network);
zv    = cba_constraints.zv;
zc    = cba_constraints.zc;
Esint = result.elasticities.un_E_c(:,ind_int);
Esext = result.elasticities.un_E_c(:,ind_ext);
Ex    = result.elasticities.un_E_u;
CJ    = result.control.CJ;
CS    = result.control.CS;
if length(cba_constraints.zc),
  w_ind   = - [[cba_constraints.zv' * Esint + cba_constraints.zc'] * L * inv(NR*Esint*L)]';
  delta_w =   [cba_constraints.zv'  * CJ - cba_constraints.zv' + cba_constraints.zc' * CS(ind_int,:)]';
% check: balance for enzymes
% [[zv'*CJ+zc'*CS(ind_int,:)] * Ex; zx']
else,
  w_ind   = - [[cba_constraints.zv' * Esint] * L * inv(NR*Esint*L)]';
  delta_w =   [cba_constraints.zv'  * CJ - cba_constraints.zv']';
% delta_w = NR' * w_ind; % alternative calculation
% check: balance for enzymes
% [[zv'*CJ] * Ex; zx']
end
% check: balance along reactions
% [ diag(v)*[zv + delta_w], diag(network.kinetics.u) * zx ]'
% insert metabolite values into full vectors (length nm)
nm             = size(network.N,1);
ind_ind        = ind_int(indep);
w_int          = nan*ones(nm,1);
w_int(ind_ind) = w_ind;
w_ext          = nan*ones(nm,1);
w_ext(ind_ext) = [zv' * CJ * Esext]';