Description of cba_economic_potentials
Home > metabolic-economics > cba_economic_potentials.m
cba_economic_potentials
PURPOSE
CBA_ECONOMIC_POTENTIALS - Compute the economic potentials and their sensitivities in a kinetic model
SYNOPSIS
function [w, v, dw_du, dv_du, c] = cba_economic_potentials(network, c, zv, zc, ind_controllable)
DESCRIPTION
 CBA_ECONOMIC_POTENTIALS - Compute the economic potentials and their sensitivities in a kinetic model
 [w, v, dw_du,  dv_du] = cba_economic_potentials(network, c, cba_constraints,ind_controllable)
 w contains only the internal economic potentials
 Compute the economic potentials for a kinetic model in a given stationary state
 as well as their derivatives dw_du with respect to the controllable enzyme levels
 The calculation works only for linear benefit functions (defined by weights zv, zc)
CROSS-REFERENCE INFORMATION
This function calls:
cba_economic_potentials CBA_ECONOMIC_POTENTIALS - Compute the economic potentials and their sensitivities in a kinetic model
This function is called by:
cba_economic_potentials CBA_ECONOMIC_POTENTIALS - Compute the economic potentials and their sensitivities in a kinetic model
cba_economic_quantities CBA_METABOLITE_AND_ENZYME_PRICES - Convenience function for computing economic quantities